/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LaurieMOO;

import java.awt.Font;

/**
 *
 * @author josephrunser
 */
public class LaurieMOOJFrame extends javax.swing.JFrame {

    private final GuessRandomValue guessRandomValue;
    private final ContentControl contentControl;
    
    private final static String BIG_MOO = "MOO!";
    private final static String LITTLE_MOO = "moo.";
    
    private final static java.util.Random RND_GEN = new java.util.Random();
    private final static Font FNT_BIG = new Font("Consolas", Font.BOLD, 48);
    private final static Font FNT_SMALL = new Font("Consolas", Font.PLAIN, 14);
    
    private static int numberOfGuesses;
    
    /**
     * Creates new form LaurieMOOGameJFrame
     */
    public LaurieMOOJFrame() {
        initComponents();
        
        guessRandomValue = new GuessRandomValue();
        contentControl = new ContentControl();
        
        contentControl.Panel_addStringCenter("Welcome to LaurieMOO!", FNT_BIG, pane_moos);
        contentControl.Panel_newGameButton(btn_newGame, FNT_BIG, pane_moos);
        
        numberOfGuesses = 0;
        guessRandomValue.setAnswer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane_moos = new javax.swing.JLayeredPane();
        btn_newGame = new javax.swing.JButton();
        txtFld_guess = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Laurie MOO!");
        setBounds(new java.awt.Rectangle(0, 22, 700, 350));
        setPreferredSize(new java.awt.Dimension(800, 600));

        pane_moos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pane_moos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btn_newGame.setText("New Game");
        btn_newGame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_newGame.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_newGame.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                btn_newGameAncestorResized(evt);
            }
        });
        btn_newGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newGameActionPerformed(evt);
            }
        });
        pane_moos.add(btn_newGame);
        btn_newGame.setBounds(310, 30, 89, 24);

        txtFld_guess.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        txtFld_guess.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFld_guess.setPreferredSize(new java.awt.Dimension(140, 70));
        txtFld_guess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFld_guessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtFld_guess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pane_moos, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFld_guess, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pane_moos, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFld_guessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFld_guessActionPerformed

        String input = txtFld_guess.getText();
        int guess;
        int littleMooCount;
        int bigMooCount;
        
        // this clears the pane so there is not many layers of text on the screen
        // maing things very messy.
        contentControl.Panel_clear(pane_moos);
        
        // error detection
        try {
            guess = Integer.parseInt(input);
        } 
        catch(NumberFormatException e) {
            guess = contentControl.Input_clean(input);
            txtFld_guess.setText("0000");
        }
        
        // Checks for a correct answer
        if(guessRandomValue.isCorrectGuess(guess) && numberOfGuesses < 9){
            bigMooCount = 4;
            
            // add required win conditions
            contentControl.Panel_addMooToPane(bigMooCount, BIG_MOO, FNT_SMALL, pane_moos);
            contentControl.Panel_addStringCenter("LaurieMOO!!!", FNT_BIG, pane_moos);
            contentControl.Panel_recenterButton(btn_newGame, FNT_BIG, pane_moos);
            
            // give a cookie
            btn_newGame.setVisible(true);
            txtFld_guess.setEnabled(false);
            txtFld_guess.setText("Win!");
        }
        // If the number of guesses is too high causing a loss
        else if(numberOfGuesses == 9) {
            // get the big and little moo counts
            littleMooCount = guessRandomValue.getLittleMooCount(guess);
            bigMooCount = guessRandomValue.getBigMooCount(guess);

            // add the moo counts and the lose condition
            contentControl.Panel_addMooToPane(littleMooCount, LITTLE_MOO, FNT_SMALL, pane_moos);
            contentControl.Panel_addMooToPane(bigMooCount, BIG_MOO, FNT_SMALL, pane_moos);
            contentControl.Panel_addStringCenter("Boo -- hoo... No LaurieMOO.", FNT_BIG, pane_moos);
            contentControl.Panel_recenterButton(btn_newGame, FNT_BIG, pane_moos);
            
            // making cheating much harder
            btn_newGame.setVisible(true);
            txtFld_guess.setEnabled(false);
            txtFld_guess.setText("Lose");
        }
        else {
            littleMooCount = guessRandomValue.getLittleMooCount(guess);
            bigMooCount = guessRandomValue.getBigMooCount(guess);
            
            contentControl.Panel_addMooToPane(littleMooCount, LITTLE_MOO, FNT_SMALL, pane_moos);
            contentControl.Panel_addMooToPane(bigMooCount, BIG_MOO, FNT_SMALL, pane_moos);
        }
        
        // Increment the lose condition
        numberOfGuesses++;
    }//GEN-LAST:event_txtFld_guessActionPerformed

    private void btn_newGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newGameActionPerformed
        
        numberOfGuesses = 0;
        
        guessRandomValue.setAnswer();
        
        txtFld_guess.setText("");
        txtFld_guess.setEnabled(true);
        btn_newGame.setVisible(false);
        
        contentControl.Panel_clear(pane_moos);
        contentControl.Panel_addStringCenter("Good luck!", FNT_BIG, pane_moos);
    }//GEN-LAST:event_btn_newGameActionPerformed

    private void btn_newGameAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_btn_newGameAncestorResized
    }//GEN-LAST:event_btn_newGameAncestorResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaurieMOOJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LaurieMOOJFrame().setVisible(true);
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_newGame;
    private javax.swing.JLayeredPane pane_moos;
    private javax.swing.JTextField txtFld_guess;
    // End of variables declaration//GEN-END:variables
}
